### ISSUE TITLE
Installing via PIP fails due to SciPy Problem (WinPython 3.5)

### ISSUE THREAD

**Issue by jcwinkler** [cklb/pymoskito#67]
Trying to install PyMoskito `using pip install pymoskito` on Windows 8.1 64-bit, WinPython 3.5.2 fails. Most obvious reason is that the requirements for SciPy leads to the attempt to build a SciPy wheel. This process fails. See attached log file.

[results.txt](https://github.com/cklb/pymoskito/files/1410275/results.txt)

**Comment by jcwinkler** [comment]
Workaround:

- Download SciPy Package from [http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy) and install the wheel using `pip install [package name]`

- Download NumPy Package from [http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) and install the wheel using `pip install [package name]`

We should mention the possibility to manually postinstall packages using this method when automatic installation fails in the installation instructions.

**Comment by cklb** [comment]
It may be the case that pip itself is the issue here. 
Instead of obtaining the wheel it tries to build one from source. This attempt fails due to missing blas/lapack libraries.

Since a win_amd64 version of scipy for python 3.5 is available on pypi it should use that one. Normally this should work without obtaining the packages manually.

To get more information on the problem:
* Which version of pip is beeing used (Winpython 3.5.2 came with pip 8.1.2) ?
* What happens when scipy is installed on its own per:  `pip install scipy` ?
* Does the behaivior change when called with: `pip install --use-wheel scipy` ?

Regards,
Stefan

**Comment by jcwinkler** [comment]
- pip version: 9.0.1

- `pip install scipy` --> exactly the same error (lapack/blas)

- `pip install --use-wheel scipy` --> exactly the same error (lapack/blas)

Jan

**Comment by cklb** [comment]
Ok my bad, version 1.0.0 of scipy will feature builds for windows but for now only 1.0.0rc2 available. (The release is late by 7 days)

So, if you are not yet tired of experimenting give `pip install -pre scipy` a shot.

Nevertheless you are right and some hints for windows users should be added to the docs.

**Comment by jcwinkler** [comment]
Warning: Installing SciPy and NumPy using the proposed way via http://www.lfd.uci.edu/~gohlke/pythonlibs makes PyMoskito to work, however renders other packages of the distribution useless due to other dependency conflicts. Hence, I do not recommend this way and we should find another solution.

**Comment by jcwinkler** [comment]
No installation problems under Winpython 3.5.4, no additional installations invoked py pip during installation of pymoskito. So that's fine.
[pymoskito-install-log.txt](https://github.com/cklb/pymoskito/files/1418945/pymoskito-install-log.txt)
